WITH cte AS (
SELECT MASTER_ID, MARKETPLACE_ID, OOS_DATE,
LAG(OOS_DATE) OVER (PARTITION BY MASTER_ID, MARKETPLACE_ID ORDER BY OOS_DATE) AS prev_date
FROM DETAILED_OOS_EVENTS
)
SELECT MASTER_ID, MARKETPLACE_ID,OOS_DATE
FROM cte
WHERE prev_date IS NULL OR DATEDIFF(OOS_DATE, prev_date) >= 7
ORDER BY MASTER_ID, MARKETPLACE_ID, OOS_DATE;